name: Build and Release PDF

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build PDF
        env:
          IMAGE: ghcr.io/afaikiac/latex-g7-32:overleaf
        run: |
          docker run --net=none -v "$PWD":/doc "$IMAGE" latexmk main

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            main.pdf
          body: |
            PDF build from commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
