name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build PDF
        env:
          IMAGE: ghcr.io/afaikiac/latex-g7-32:overleaf
        run: |
          docker run --net=none -v "$PWD":/doc "$IMAGE" latexmk -pdfxe main

      - name: Create zip file
        run: |
          zip -r latex-g7-32.zip lib res tex .latexmkrc main.tex

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            main.pdf
            latex-g7-32.zip
          body: |
            PDF build from commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
